version: '3.8'

services:
  skistore_frontend:
    container_name: skistore_frontend
    build:
      context: ./
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING="true"
    ports:
      - "3000:5173"
    stdin_open: true
    volumes:
      - ./:/app
      - /app/node_modules

